// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zambia_Police_Service.WEB
{
    public partial class Crimes
    {
        public int CrimeId { get; set; }
        public string CrimeLocation { get; set; }
        public int? UserNumber { get; set; }
        public string CrimePath { get; set; }

        public virtual PoliceUsers UserNumberNavigation { get; set; }
    }
}