// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zambia_Police_Service.WEB
{
    public partial class MissingPersons
    {
        public int MissingPersonId { get; set; }
        public string MissingPersonLocation { get; set; }
        public int? UserNumber { get; set; }
        public string MissingPersonPath { get; set; }

        public virtual PoliceUsers UserNumberNavigation { get; set; }
    }
}