// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zambia_Police_Service.WEB
{
    public partial class PoliceAdmins
    {
        public int Id { get; set; }
        public string AdminName { get; set; }
        public string AdminAddress { get; set; }
        public string AdminEmailAddress { get; set; }
        public string AdminPosition { get; set; }
        public string AdminWorkStation { get; set; }
        public string AdminLocation { get; set; }
        public int AdminNumber { get; set; }
    }
}