// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zambia_Police_Service.WEB
{
    public partial class PoliceUsers
    {
        public PoliceUsers()
        {
            Complaints = new HashSet<Complaints>();
            Crimes = new HashSet<Crimes>();
            MissingPersons = new HashSet<MissingPersons>();
        }

        public int UserId { get; set; }
        public string UserFullName { get; set; }
        public string UserEmailAddress { get; set; }
        public string UserLocation { get; set; }
        public int UserNumber { get; set; }

        public virtual ICollection<Complaints> Complaints { get; set; }
        public virtual ICollection<Crimes> Crimes { get; set; }
        public virtual ICollection<MissingPersons> MissingPersons { get; set; }
    }
}